baseURL = "http://hub.waterloop.ca/"
languageCode = "en-us"
title = "Waterloop hub"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "chat"
tag = "chat"
icon = "inbox"

[[ params.nav ]]
name = "documents"
tag = "documents"
icon = "book"

[[ params.nav ]]
name = "tasks"
tag = "tasks"
icon = "cog"

[[ params.nav ]]
name = "code"
tag = "code"
icon = "laptop"
